services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/app
    image: 'checkers-bot'
    environment:
      CONFIG: ./config/local.yaml
    ports:
      - "8080:8080"
    container_name: checkers-bot
    command: watchfiles "python3 -m bot.main" bot
    tty: true
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: checkers-bot-postgres
    image: postgres:17
    volumes:
      - postgres_local_data:/var/lib/postgresql/data/
    ports:
      - "8082:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=checkers

volumes:
  postgres_local_data: {}
